// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: eth/v1alpha1/shard.proto

package eth

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ShardBlock struct {
	ShardParentRoot      []byte   `protobuf:"bytes,1,opt,name=shard_parent_root,json=shardParentRoot,proto3" json:"shard_parent_root,omitempty" ssz-size:"32"`
	BeaconParentRoot     []byte   `protobuf:"bytes,2,opt,name=beacon_parent_root,json=beaconParentRoot,proto3" json:"beacon_parent_root,omitempty" ssz-size:"32"`
	Slot                 uint64   `protobuf:"varint,3,opt,name=slot,proto3" json:"slot,omitempty"`
	ProposerIndex        uint64   `protobuf:"varint,4,opt,name=proposer_index,json=proposerIndex,proto3" json:"proposer_index,omitempty"`
	Body                 [][]byte `protobuf:"bytes,5,rep,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShardBlock) Reset()         { *m = ShardBlock{} }
func (m *ShardBlock) String() string { return proto.CompactTextString(m) }
func (*ShardBlock) ProtoMessage()    {}
func (*ShardBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d9da510e571288b, []int{0}
}
func (m *ShardBlock) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ShardBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ShardBlock.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ShardBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardBlock.Merge(m, src)
}
func (m *ShardBlock) XXX_Size() int {
	return m.Size()
}
func (m *ShardBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardBlock.DiscardUnknown(m)
}

var xxx_messageInfo_ShardBlock proto.InternalMessageInfo

func (m *ShardBlock) GetShardParentRoot() []byte {
	if m != nil {
		return m.ShardParentRoot
	}
	return nil
}

func (m *ShardBlock) GetBeaconParentRoot() []byte {
	if m != nil {
		return m.BeaconParentRoot
	}
	return nil
}

func (m *ShardBlock) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *ShardBlock) GetProposerIndex() uint64 {
	if m != nil {
		return m.ProposerIndex
	}
	return 0
}

func (m *ShardBlock) GetBody() [][]byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type SignedShardBlock struct {
	Message              *ShardBlock `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Signature            []byte      `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty" ssz-size:"96"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SignedShardBlock) Reset()         { *m = SignedShardBlock{} }
func (m *SignedShardBlock) String() string { return proto.CompactTextString(m) }
func (*SignedShardBlock) ProtoMessage()    {}
func (*SignedShardBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d9da510e571288b, []int{1}
}
func (m *SignedShardBlock) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SignedShardBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SignedShardBlock.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SignedShardBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedShardBlock.Merge(m, src)
}
func (m *SignedShardBlock) XXX_Size() int {
	return m.Size()
}
func (m *SignedShardBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedShardBlock.DiscardUnknown(m)
}

var xxx_messageInfo_SignedShardBlock proto.InternalMessageInfo

func (m *SignedShardBlock) GetMessage() *ShardBlock {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *SignedShardBlock) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type ShardBlockHeader struct {
	ShardParentRoot      []byte   `protobuf:"bytes,1,opt,name=shard_parent_root,json=shardParentRoot,proto3" json:"shard_parent_root,omitempty" ssz-size:"32"`
	BeaconParentRoot     []byte   `protobuf:"bytes,2,opt,name=beacon_parent_root,json=beaconParentRoot,proto3" json:"beacon_parent_root,omitempty" ssz-size:"32"`
	Slot                 uint64   `protobuf:"varint,3,opt,name=slot,proto3" json:"slot,omitempty"`
	ProposerIndex        uint64   `protobuf:"varint,4,opt,name=proposer_index,json=proposerIndex,proto3" json:"proposer_index,omitempty"`
	BodyRoot             []byte   `protobuf:"bytes,5,opt,name=body_root,json=bodyRoot,proto3" json:"body_root,omitempty" ssz-size:"32"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShardBlockHeader) Reset()         { *m = ShardBlockHeader{} }
func (m *ShardBlockHeader) String() string { return proto.CompactTextString(m) }
func (*ShardBlockHeader) ProtoMessage()    {}
func (*ShardBlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d9da510e571288b, []int{2}
}
func (m *ShardBlockHeader) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ShardBlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ShardBlockHeader.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ShardBlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardBlockHeader.Merge(m, src)
}
func (m *ShardBlockHeader) XXX_Size() int {
	return m.Size()
}
func (m *ShardBlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardBlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ShardBlockHeader proto.InternalMessageInfo

func (m *ShardBlockHeader) GetShardParentRoot() []byte {
	if m != nil {
		return m.ShardParentRoot
	}
	return nil
}

func (m *ShardBlockHeader) GetBeaconParentRoot() []byte {
	if m != nil {
		return m.BeaconParentRoot
	}
	return nil
}

func (m *ShardBlockHeader) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *ShardBlockHeader) GetProposerIndex() uint64 {
	if m != nil {
		return m.ProposerIndex
	}
	return 0
}

func (m *ShardBlockHeader) GetBodyRoot() []byte {
	if m != nil {
		return m.BodyRoot
	}
	return nil
}

type ShardState struct {
	Slot                 uint64   `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	GasPrice             uint64   `protobuf:"varint,2,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	TransitionDigest     []byte   `protobuf:"bytes,3,opt,name=transition_digest,json=transitionDigest,proto3" json:"transition_digest,omitempty" ssz-size:"32"`
	LatestBlockRoot      []byte   `protobuf:"bytes,4,opt,name=latest_block_root,json=latestBlockRoot,proto3" json:"latest_block_root,omitempty" ssz-size:"32"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShardState) Reset()         { *m = ShardState{} }
func (m *ShardState) String() string { return proto.CompactTextString(m) }
func (*ShardState) ProtoMessage()    {}
func (*ShardState) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d9da510e571288b, []int{3}
}
func (m *ShardState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ShardState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ShardState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ShardState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardState.Merge(m, src)
}
func (m *ShardState) XXX_Size() int {
	return m.Size()
}
func (m *ShardState) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardState.DiscardUnknown(m)
}

var xxx_messageInfo_ShardState proto.InternalMessageInfo

func (m *ShardState) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *ShardState) GetGasPrice() uint64 {
	if m != nil {
		return m.GasPrice
	}
	return 0
}

func (m *ShardState) GetTransitionDigest() []byte {
	if m != nil {
		return m.TransitionDigest
	}
	return nil
}

func (m *ShardState) GetLatestBlockRoot() []byte {
	if m != nil {
		return m.LatestBlockRoot
	}
	return nil
}

type ShardTransition struct {
	StartSlot                  uint64        `protobuf:"varint,1,opt,name=start_slot,json=startSlot,proto3" json:"start_slot,omitempty"`
	ShardBlockLengths          []uint64      `protobuf:"varint,2,rep,packed,name=shard_block_lengths,json=shardBlockLengths,proto3" json:"shard_block_lengths,omitempty" ssz-max:"2048"`
	ShardDataRoots             [][]byte      `protobuf:"bytes,3,rep,name=shard_data_roots,json=shardDataRoots,proto3" json:"shard_data_roots,omitempty" ssz-size:"32,2048"`
	ShardStates                []*ShardState `protobuf:"bytes,4,rep,name=shard_states,json=shardStates,proto3" json:"shard_states,omitempty" ssz-max:"2048"`
	ProposerSignatureAggregate []byte        `protobuf:"bytes,5,opt,name=proposer_signature_aggregate,json=proposerSignatureAggregate,proto3" json:"proposer_signature_aggregate,omitempty" ssz-size:"96"`
	XXX_NoUnkeyedLiteral       struct{}      `json:"-"`
	XXX_unrecognized           []byte        `json:"-"`
	XXX_sizecache              int32         `json:"-"`
}

func (m *ShardTransition) Reset()         { *m = ShardTransition{} }
func (m *ShardTransition) String() string { return proto.CompactTextString(m) }
func (*ShardTransition) ProtoMessage()    {}
func (*ShardTransition) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d9da510e571288b, []int{4}
}
func (m *ShardTransition) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ShardTransition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ShardTransition.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ShardTransition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardTransition.Merge(m, src)
}
func (m *ShardTransition) XXX_Size() int {
	return m.Size()
}
func (m *ShardTransition) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardTransition.DiscardUnknown(m)
}

var xxx_messageInfo_ShardTransition proto.InternalMessageInfo

func (m *ShardTransition) GetStartSlot() uint64 {
	if m != nil {
		return m.StartSlot
	}
	return 0
}

func (m *ShardTransition) GetShardBlockLengths() []uint64 {
	if m != nil {
		return m.ShardBlockLengths
	}
	return nil
}

func (m *ShardTransition) GetShardDataRoots() [][]byte {
	if m != nil {
		return m.ShardDataRoots
	}
	return nil
}

func (m *ShardTransition) GetShardStates() []*ShardState {
	if m != nil {
		return m.ShardStates
	}
	return nil
}

func (m *ShardTransition) GetProposerSignatureAggregate() []byte {
	if m != nil {
		return m.ProposerSignatureAggregate
	}
	return nil
}

type CompactCommittee struct {
	PubKeys              [][]byte `protobuf:"bytes,2,rep,name=pub_keys,json=pubKeys,proto3" json:"pub_keys,omitempty" ssz-max:"48,2048"`
	CompactValidators    []uint64 `protobuf:"varint,3,rep,packed,name=compact_validators,json=compactValidators,proto3" json:"compact_validators,omitempty" ssz-size:"2048"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompactCommittee) Reset()         { *m = CompactCommittee{} }
func (m *CompactCommittee) String() string { return proto.CompactTextString(m) }
func (*CompactCommittee) ProtoMessage()    {}
func (*CompactCommittee) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d9da510e571288b, []int{5}
}
func (m *CompactCommittee) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CompactCommittee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CompactCommittee.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CompactCommittee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompactCommittee.Merge(m, src)
}
func (m *CompactCommittee) XXX_Size() int {
	return m.Size()
}
func (m *CompactCommittee) XXX_DiscardUnknown() {
	xxx_messageInfo_CompactCommittee.DiscardUnknown(m)
}

var xxx_messageInfo_CompactCommittee proto.InternalMessageInfo

func (m *CompactCommittee) GetPubKeys() [][]byte {
	if m != nil {
		return m.PubKeys
	}
	return nil
}

func (m *CompactCommittee) GetCompactValidators() []uint64 {
	if m != nil {
		return m.CompactValidators
	}
	return nil
}

func init() {
	proto.RegisterType((*ShardBlock)(nil), "ethereum.eth.v1alpha1.ShardBlock")
	proto.RegisterType((*SignedShardBlock)(nil), "ethereum.eth.v1alpha1.SignedShardBlock")
	proto.RegisterType((*ShardBlockHeader)(nil), "ethereum.eth.v1alpha1.ShardBlockHeader")
	proto.RegisterType((*ShardState)(nil), "ethereum.eth.v1alpha1.ShardState")
	proto.RegisterType((*ShardTransition)(nil), "ethereum.eth.v1alpha1.ShardTransition")
	proto.RegisterType((*CompactCommittee)(nil), "ethereum.eth.v1alpha1.CompactCommittee")
}

func init() { proto.RegisterFile("eth/v1alpha1/shard.proto", fileDescriptor_5d9da510e571288b) }

var fileDescriptor_5d9da510e571288b = []byte{
	// 697 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x54, 0xcd, 0x6a, 0xdb, 0x4a,
	0x18, 0x45, 0xb6, 0x72, 0x13, 0x4f, 0x9c, 0xc4, 0x9e, 0x90, 0x8b, 0xc8, 0xbd, 0x8d, 0x5d, 0x41,
	0xc1, 0x8b, 0xc6, 0xce, 0x1f, 0x21, 0x4d, 0xe8, 0x9f, 0x92, 0x40, 0x4b, 0xbb, 0x08, 0x72, 0x29,
	0xa5, 0x14, 0xc4, 0xc8, 0x9a, 0x4a, 0x22, 0x96, 0x46, 0xcc, 0x7c, 0x0e, 0x71, 0x56, 0x5d, 0xf6,
	0x59, 0xfa, 0x0c, 0x7d, 0x80, 0x2e, 0xbb, 0x2f, 0x98, 0x12, 0xe8, 0x0b, 0x78, 0x5f, 0x28, 0x33,
	0x13, 0xc9, 0x2e, 0x38, 0x74, 0xdd, 0xdd, 0xcc, 0xe8, 0x7c, 0xe7, 0x9c, 0xef, 0xcc, 0xa7, 0x41,
	0x16, 0x85, 0xa8, 0x73, 0xb1, 0x4d, 0xfa, 0x59, 0x44, 0xb6, 0x3b, 0x22, 0x22, 0x3c, 0x68, 0x67,
	0x9c, 0x01, 0xc3, 0x6b, 0x14, 0x22, 0xca, 0xe9, 0x20, 0x69, 0x53, 0x88, 0xda, 0x39, 0x64, 0x7d,
	0x33, 0x8c, 0x21, 0x1a, 0xf8, 0xed, 0x1e, 0x4b, 0x3a, 0x21, 0x0b, 0x59, 0x47, 0xa1, 0xfd, 0xc1,
	0x7b, 0xb5, 0x53, 0x1b, 0xb5, 0xd2, 0x2c, 0xf6, 0x37, 0x03, 0xa1, 0xae, 0x64, 0x75, 0xfa, 0xac,
	0x77, 0x8e, 0x1f, 0xa2, 0xba, 0xd2, 0xf0, 0x32, 0xc2, 0x69, 0x0a, 0x1e, 0x67, 0x0c, 0x2c, 0xa3,
	0x69, 0xb4, 0xaa, 0x4e, 0x7d, 0x3c, 0x6a, 0x2c, 0x09, 0x71, 0xb5, 0x29, 0xe2, 0x2b, 0x7a, 0x68,
	0xef, 0xee, 0xd8, 0xee, 0x8a, 0xc2, 0x9e, 0x29, 0xa8, 0xcb, 0x18, 0xe0, 0xc7, 0x08, 0xfb, 0x94,
	0xf4, 0x58, 0xfa, 0x5b, 0x7d, 0xe9, 0xb6, 0xfa, 0x9a, 0x06, 0x4f, 0x11, 0x60, 0x64, 0x8a, 0x3e,
	0x03, 0xab, 0xdc, 0x34, 0x5a, 0xa6, 0xab, 0xd6, 0xf8, 0x1e, 0x5a, 0xce, 0x38, 0xcb, 0x98, 0xa0,
	0xdc, 0x8b, 0xd3, 0x80, 0x5e, 0x5a, 0xa6, 0xfa, 0xba, 0x94, 0x9f, 0x3e, 0x97, 0x87, 0xb2, 0xd4,
	0x67, 0xc1, 0xd0, 0x9a, 0x6b, 0x96, 0x5b, 0x55, 0x57, 0xad, 0xed, 0x0f, 0x06, 0xaa, 0x75, 0xe3,
	0x30, 0xa5, 0xc1, 0x54, 0x8f, 0x47, 0x68, 0x3e, 0xa1, 0x42, 0x90, 0x90, 0xaa, 0xce, 0x16, 0x77,
	0xee, 0xb6, 0x67, 0x46, 0xd9, 0x9e, 0xd4, 0xb8, 0x79, 0x05, 0xee, 0xa0, 0x8a, 0x88, 0xc3, 0x94,
	0xc0, 0x80, 0xd3, 0xd9, 0x8d, 0x3d, 0xd8, 0xb7, 0xdd, 0x09, 0xc6, 0xfe, 0x29, 0x2d, 0x14, 0x44,
	0xcf, 0x28, 0x09, 0x28, 0xff, 0x9b, 0x63, 0x6e, 0xa3, 0x8a, 0x8c, 0x56, 0x4b, 0xce, 0xdd, 0x26,
	0xb9, 0x20, 0x31, 0x52, 0xca, 0xfe, 0x9c, 0x0f, 0x58, 0x17, 0x08, 0xd0, 0x42, 0xd9, 0x98, 0x52,
	0xfe, 0x0f, 0x55, 0x42, 0x22, 0xbc, 0x8c, 0xc7, 0x3d, 0x9d, 0xa9, 0xe9, 0x2e, 0x84, 0x44, 0x9c,
	0xc9, 0x3d, 0x7e, 0x84, 0xea, 0xc0, 0x49, 0x2a, 0x62, 0x88, 0x59, 0xea, 0x05, 0x71, 0x48, 0x85,
	0xf6, 0x3d, 0xbb, 0xd5, 0x09, 0xf6, 0x44, 0x41, 0x65, 0xd4, 0x7d, 0x02, 0x54, 0x80, 0xe7, 0xcb,
	0x0b, 0xd0, 0xbe, 0xcd, 0x5b, 0xa3, 0xd6, 0x58, 0x7d, 0xe9, 0xd2, 0xfe, 0x8f, 0x12, 0x5a, 0x51,
	0xf6, 0x5f, 0x15, 0xc4, 0xf8, 0x0e, 0x42, 0x02, 0x08, 0x07, 0x6f, 0xaa, 0x93, 0x8a, 0x3a, 0xe9,
	0xca, 0x76, 0x1c, 0xb4, 0xaa, 0x2f, 0x57, 0x0b, 0xf6, 0x69, 0x1a, 0x42, 0x24, 0xac, 0x52, 0xb3,
	0xdc, 0x32, 0x1d, 0x3c, 0x1e, 0x35, 0x96, 0xa5, 0x66, 0x42, 0x2e, 0x0f, 0xed, 0x9d, 0xad, 0xbd,
	0x03, 0xdb, 0xd5, 0xb3, 0xa0, 0x34, 0x5f, 0x6a, 0x30, 0x7e, 0x82, 0x6a, 0x9a, 0x23, 0x20, 0x40,
	0x94, 0x67, 0x61, 0x95, 0xe5, 0x60, 0x3b, 0xff, 0x8e, 0x47, 0x0d, 0x3c, 0x6d, 0xfa, 0xbe, 0x26,
	0x59, 0x56, 0xf8, 0x13, 0x02, 0x44, 0xfa, 0x16, 0xf8, 0x0d, 0xaa, 0x6a, 0x06, 0x21, 0x73, 0x17,
	0x96, 0xd9, 0x2c, 0xff, 0x69, 0xd4, 0xd5, 0x0d, 0xcd, 0x74, 0xb8, 0x28, 0x8a, 0xef, 0x02, 0x77,
	0xd1, 0xff, 0xc5, 0xa0, 0x14, 0x73, 0xee, 0x91, 0x30, 0xe4, 0x34, 0x24, 0x40, 0x67, 0x0f, 0x85,
	0xfc, 0x2b, 0xd6, 0xf3, 0xb2, 0x6e, 0x5e, 0xf5, 0x34, 0x2f, 0xb2, 0x3f, 0x1a, 0xa8, 0x76, 0xcc,
	0x92, 0x8c, 0xf4, 0xe0, 0x98, 0x25, 0x49, 0x0c, 0x40, 0x29, 0xde, 0x42, 0x0b, 0xd9, 0xc0, 0xf7,
	0xce, 0xe9, 0x50, 0xc7, 0x57, 0x75, 0xd6, 0xc6, 0xa3, 0x46, 0xbd, 0x30, 0xb7, 0x77, 0x70, 0xd3,
	0xfc, 0x7c, 0x36, 0xf0, 0x5f, 0xd0, 0xa1, 0xc0, 0x0e, 0xc2, 0x3d, 0xcd, 0xe2, 0x5d, 0x90, 0x7e,
	0x1c, 0x10, 0x60, 0x5c, 0x27, 0x67, 0x3a, 0xab, 0xe3, 0x51, 0x63, 0x65, 0xe2, 0xe8, 0x26, 0xfb,
	0x1b, 0xf8, 0xeb, 0x02, 0xed, 0xbc, 0xfb, 0x72, 0xbd, 0x61, 0x7c, 0xbd, 0xde, 0x30, 0xbe, 0x5f,
	0x6f, 0x18, 0x6f, 0xf7, 0xa7, 0xde, 0xd3, 0x8c, 0x0f, 0x45, 0x42, 0x20, 0xee, 0xf5, 0x89, 0x2f,
	0x3a, 0x79, 0x92, 0x24, 0x8b, 0xd5, 0xa6, 0x78, 0xa6, 0x8f, 0x28, 0x44, 0x9f, 0x4a, 0x6b, 0xa7,
	0x79, 0xd2, 0xa7, 0x53, 0x49, 0xfb, 0xff, 0xa8, 0x77, 0x77, 0xf7, 0x57, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x2d, 0xbc, 0x0a, 0xe9, 0xd9, 0x05, 0x00, 0x00,
}

func (m *ShardBlock) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ShardBlock) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ShardParentRoot) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintShard(dAtA, i, uint64(len(m.ShardParentRoot)))
		i += copy(dAtA[i:], m.ShardParentRoot)
	}
	if len(m.BeaconParentRoot) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintShard(dAtA, i, uint64(len(m.BeaconParentRoot)))
		i += copy(dAtA[i:], m.BeaconParentRoot)
	}
	if m.Slot != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintShard(dAtA, i, uint64(m.Slot))
	}
	if m.ProposerIndex != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintShard(dAtA, i, uint64(m.ProposerIndex))
	}
	if len(m.Body) > 0 {
		for _, b := range m.Body {
			dAtA[i] = 0x2a
			i++
			i = encodeVarintShard(dAtA, i, uint64(len(b)))
			i += copy(dAtA[i:], b)
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *SignedShardBlock) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SignedShardBlock) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Message != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintShard(dAtA, i, uint64(m.Message.Size()))
		n1, err := m.Message.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if len(m.Signature) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintShard(dAtA, i, uint64(len(m.Signature)))
		i += copy(dAtA[i:], m.Signature)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ShardBlockHeader) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ShardBlockHeader) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ShardParentRoot) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintShard(dAtA, i, uint64(len(m.ShardParentRoot)))
		i += copy(dAtA[i:], m.ShardParentRoot)
	}
	if len(m.BeaconParentRoot) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintShard(dAtA, i, uint64(len(m.BeaconParentRoot)))
		i += copy(dAtA[i:], m.BeaconParentRoot)
	}
	if m.Slot != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintShard(dAtA, i, uint64(m.Slot))
	}
	if m.ProposerIndex != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintShard(dAtA, i, uint64(m.ProposerIndex))
	}
	if len(m.BodyRoot) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintShard(dAtA, i, uint64(len(m.BodyRoot)))
		i += copy(dAtA[i:], m.BodyRoot)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ShardState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ShardState) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Slot != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintShard(dAtA, i, uint64(m.Slot))
	}
	if m.GasPrice != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintShard(dAtA, i, uint64(m.GasPrice))
	}
	if len(m.TransitionDigest) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintShard(dAtA, i, uint64(len(m.TransitionDigest)))
		i += copy(dAtA[i:], m.TransitionDigest)
	}
	if len(m.LatestBlockRoot) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintShard(dAtA, i, uint64(len(m.LatestBlockRoot)))
		i += copy(dAtA[i:], m.LatestBlockRoot)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ShardTransition) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ShardTransition) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.StartSlot != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintShard(dAtA, i, uint64(m.StartSlot))
	}
	if len(m.ShardBlockLengths) > 0 {
		dAtA3 := make([]byte, len(m.ShardBlockLengths)*10)
		var j2 int
		for _, num := range m.ShardBlockLengths {
			for num >= 1<<7 {
				dAtA3[j2] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j2++
			}
			dAtA3[j2] = uint8(num)
			j2++
		}
		dAtA[i] = 0x12
		i++
		i = encodeVarintShard(dAtA, i, uint64(j2))
		i += copy(dAtA[i:], dAtA3[:j2])
	}
	if len(m.ShardDataRoots) > 0 {
		for _, b := range m.ShardDataRoots {
			dAtA[i] = 0x1a
			i++
			i = encodeVarintShard(dAtA, i, uint64(len(b)))
			i += copy(dAtA[i:], b)
		}
	}
	if len(m.ShardStates) > 0 {
		for _, msg := range m.ShardStates {
			dAtA[i] = 0x22
			i++
			i = encodeVarintShard(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.ProposerSignatureAggregate) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintShard(dAtA, i, uint64(len(m.ProposerSignatureAggregate)))
		i += copy(dAtA[i:], m.ProposerSignatureAggregate)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *CompactCommittee) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CompactCommittee) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.PubKeys) > 0 {
		for _, b := range m.PubKeys {
			dAtA[i] = 0x12
			i++
			i = encodeVarintShard(dAtA, i, uint64(len(b)))
			i += copy(dAtA[i:], b)
		}
	}
	if len(m.CompactValidators) > 0 {
		dAtA5 := make([]byte, len(m.CompactValidators)*10)
		var j4 int
		for _, num := range m.CompactValidators {
			for num >= 1<<7 {
				dAtA5[j4] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j4++
			}
			dAtA5[j4] = uint8(num)
			j4++
		}
		dAtA[i] = 0x1a
		i++
		i = encodeVarintShard(dAtA, i, uint64(j4))
		i += copy(dAtA[i:], dAtA5[:j4])
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintShard(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *ShardBlock) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ShardParentRoot)
	if l > 0 {
		n += 1 + l + sovShard(uint64(l))
	}
	l = len(m.BeaconParentRoot)
	if l > 0 {
		n += 1 + l + sovShard(uint64(l))
	}
	if m.Slot != 0 {
		n += 1 + sovShard(uint64(m.Slot))
	}
	if m.ProposerIndex != 0 {
		n += 1 + sovShard(uint64(m.ProposerIndex))
	}
	if len(m.Body) > 0 {
		for _, b := range m.Body {
			l = len(b)
			n += 1 + l + sovShard(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SignedShardBlock) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Message != nil {
		l = m.Message.Size()
		n += 1 + l + sovShard(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovShard(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ShardBlockHeader) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ShardParentRoot)
	if l > 0 {
		n += 1 + l + sovShard(uint64(l))
	}
	l = len(m.BeaconParentRoot)
	if l > 0 {
		n += 1 + l + sovShard(uint64(l))
	}
	if m.Slot != 0 {
		n += 1 + sovShard(uint64(m.Slot))
	}
	if m.ProposerIndex != 0 {
		n += 1 + sovShard(uint64(m.ProposerIndex))
	}
	l = len(m.BodyRoot)
	if l > 0 {
		n += 1 + l + sovShard(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ShardState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Slot != 0 {
		n += 1 + sovShard(uint64(m.Slot))
	}
	if m.GasPrice != 0 {
		n += 1 + sovShard(uint64(m.GasPrice))
	}
	l = len(m.TransitionDigest)
	if l > 0 {
		n += 1 + l + sovShard(uint64(l))
	}
	l = len(m.LatestBlockRoot)
	if l > 0 {
		n += 1 + l + sovShard(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ShardTransition) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.StartSlot != 0 {
		n += 1 + sovShard(uint64(m.StartSlot))
	}
	if len(m.ShardBlockLengths) > 0 {
		l = 0
		for _, e := range m.ShardBlockLengths {
			l += sovShard(uint64(e))
		}
		n += 1 + sovShard(uint64(l)) + l
	}
	if len(m.ShardDataRoots) > 0 {
		for _, b := range m.ShardDataRoots {
			l = len(b)
			n += 1 + l + sovShard(uint64(l))
		}
	}
	if len(m.ShardStates) > 0 {
		for _, e := range m.ShardStates {
			l = e.Size()
			n += 1 + l + sovShard(uint64(l))
		}
	}
	l = len(m.ProposerSignatureAggregate)
	if l > 0 {
		n += 1 + l + sovShard(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *CompactCommittee) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.PubKeys) > 0 {
		for _, b := range m.PubKeys {
			l = len(b)
			n += 1 + l + sovShard(uint64(l))
		}
	}
	if len(m.CompactValidators) > 0 {
		l = 0
		for _, e := range m.CompactValidators {
			l += sovShard(uint64(e))
		}
		n += 1 + sovShard(uint64(l)) + l
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovShard(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozShard(x uint64) (n int) {
	return sovShard(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ShardBlock) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowShard
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ShardBlock: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ShardBlock: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShardParentRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthShard
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthShard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ShardParentRoot = append(m.ShardParentRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.ShardParentRoot == nil {
				m.ShardParentRoot = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BeaconParentRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthShard
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthShard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BeaconParentRoot = append(m.BeaconParentRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.BeaconParentRoot == nil {
				m.BeaconParentRoot = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Slot", wireType)
			}
			m.Slot = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Slot |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposerIndex", wireType)
			}
			m.ProposerIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProposerIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Body", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthShard
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthShard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Body = append(m.Body, make([]byte, postIndex-iNdEx))
			copy(m.Body[len(m.Body)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipShard(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthShard
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthShard
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SignedShardBlock) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowShard
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SignedShardBlock: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SignedShardBlock: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthShard
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthShard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Message == nil {
				m.Message = &ShardBlock{}
			}
			if err := m.Message.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthShard
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthShard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipShard(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthShard
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthShard
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ShardBlockHeader) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowShard
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ShardBlockHeader: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ShardBlockHeader: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShardParentRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthShard
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthShard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ShardParentRoot = append(m.ShardParentRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.ShardParentRoot == nil {
				m.ShardParentRoot = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BeaconParentRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthShard
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthShard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BeaconParentRoot = append(m.BeaconParentRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.BeaconParentRoot == nil {
				m.BeaconParentRoot = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Slot", wireType)
			}
			m.Slot = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Slot |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposerIndex", wireType)
			}
			m.ProposerIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProposerIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BodyRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthShard
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthShard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BodyRoot = append(m.BodyRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.BodyRoot == nil {
				m.BodyRoot = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipShard(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthShard
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthShard
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ShardState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowShard
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ShardState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ShardState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Slot", wireType)
			}
			m.Slot = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Slot |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasPrice", wireType)
			}
			m.GasPrice = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GasPrice |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransitionDigest", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthShard
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthShard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TransitionDigest = append(m.TransitionDigest[:0], dAtA[iNdEx:postIndex]...)
			if m.TransitionDigest == nil {
				m.TransitionDigest = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestBlockRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthShard
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthShard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LatestBlockRoot = append(m.LatestBlockRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.LatestBlockRoot == nil {
				m.LatestBlockRoot = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipShard(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthShard
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthShard
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ShardTransition) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowShard
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ShardTransition: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ShardTransition: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartSlot", wireType)
			}
			m.StartSlot = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartSlot |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowShard
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.ShardBlockLengths = append(m.ShardBlockLengths, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowShard
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthShard
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthShard
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.ShardBlockLengths) == 0 {
					m.ShardBlockLengths = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowShard
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.ShardBlockLengths = append(m.ShardBlockLengths, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field ShardBlockLengths", wireType)
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShardDataRoots", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthShard
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthShard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ShardDataRoots = append(m.ShardDataRoots, make([]byte, postIndex-iNdEx))
			copy(m.ShardDataRoots[len(m.ShardDataRoots)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShardStates", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthShard
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthShard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ShardStates = append(m.ShardStates, &ShardState{})
			if err := m.ShardStates[len(m.ShardStates)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposerSignatureAggregate", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthShard
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthShard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProposerSignatureAggregate = append(m.ProposerSignatureAggregate[:0], dAtA[iNdEx:postIndex]...)
			if m.ProposerSignatureAggregate == nil {
				m.ProposerSignatureAggregate = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipShard(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthShard
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthShard
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CompactCommittee) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowShard
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CompactCommittee: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CompactCommittee: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubKeys", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShard
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthShard
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthShard
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PubKeys = append(m.PubKeys, make([]byte, postIndex-iNdEx))
			copy(m.PubKeys[len(m.PubKeys)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowShard
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.CompactValidators = append(m.CompactValidators, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowShard
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthShard
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthShard
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.CompactValidators) == 0 {
					m.CompactValidators = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowShard
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.CompactValidators = append(m.CompactValidators, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field CompactValidators", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipShard(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthShard
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthShard
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipShard(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowShard
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowShard
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowShard
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthShard
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthShard
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowShard
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipShard(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthShard
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthShard = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowShard   = fmt.Errorf("proto: integer overflow")
)
